{{- define "propeller.secrets.tpl" -}}
{{- if .Values.imageCredentials }}
{{- range $s := .Values.imageCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $s.name }}
  labels:
    {{- include "propeller.chartLabels" . | indent 4 }}
    {{- include "propeller.helmLabels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" $s.registry (printf "%s:%s" $s.username $s.password | b64enc) | b64enc }}
{{- end }}
{{- end }}
{{- if .Values.secrets }}
{{- range $name, $keys := .Values.secrets }}
{{- if $keys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "propeller.chartLabels" . | indent 4 }}
    {{- include "propeller.helmLabels" . | indent 4 }}
type: Opaque
data:
  {{- range $k, $v := $keys }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
