{{- define "propeller.serviceaccount.tpl" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.canary }}
  name: {{ .Values.serviceAccount.name }}-canary
  {{- else }}
  name: {{ .Values.serviceAccount.name }}
  {{- end }}
  labels:
    account: {{ .Values.serviceAccount.account }}
    {{- include "propeller.chartLabels" . | indent 4 }}
    {{- include "propeller.helmLabels" . | indent 4 }}
imagePullSecrets:
{{- range $_, $s := .Values.imagePullSecrets }}
- name: {{ $s.name }}
{{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  {{- if .Values.canary }}
  name: {{ .Values.serviceAccount.name }}-canary
  {{- else }}
  name: {{ .Values.serviceAccount.name  }}
  {{- end }}
  labels:
    account: {{ .Values.serviceAccount.account }}
    {{- include "propeller.chartLabels" . | indent 4 }}
    {{- include "propeller.helmLabels" . | indent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
    - events
  verbs:
    - get
    - post
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  {{- if .Values.canary }}
  name: {{ .Values.serviceAccount.name }}-canary
  {{- else }}
  name: {{ .Values.serviceAccount.name }}
  {{- end }}
  labels:
    account: {{ .Values.serviceAccount.account }}
    {{- include "propeller.chartLabels" . | indent 4 }}
    {{- include "propeller.helmLabels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  {{- if .Values.canary }}
  name: {{ .Values.serviceAccount.name }}-canary
  {{- else }}
  name: {{ .Values.serviceAccount.name }}
  {{- end }}
subjects:
- kind: ServiceAccount
  {{- if .Values.canary }}
  name: {{ .Values.serviceAccount.name }}-canary
  {{- else }}
  name: {{ .Values.serviceAccount.name }}
  {{- end }}
{{- end }}
