{{- define "propeller.statefulset.tpl" -}}
{{- $deploymentType := .Values.deploymentType | default "Deployment" -}}
{{- if and .Values.appInitializement .Values.appInitializement.configFiles }}
{{- range $i, $c := .Values.appInitializement.configFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "propeller.appName" $ }}-prepare-{{ $i }}
  labels:
    {{- include "propeller.chartLabels" $ | indent 4 }}
    {{- include "propeller.helmLabels" $ | indent 4 }}
data:
  prepare-{{ $i }}.sh: |
    #!sh
    {{- range $f := $c.files }}
    {{- if $.Values.labels.baseimage }}
    {{- if eq $.Values.labels.baseimage "ubuntu" }}
    cmd="echo"
    {{- else }}
    cmd="echo -e"
    {{- end }}
    {{- else }}
    cmd="echo -e"
    {{- end }}
    templ=`cat {{ $c.path }}/{{ $f.templateFile }}`
    {{- if $f.exTemplate }}
    extempl=`cat {{ $f.exTemplate }}`
    ${cmd} "cat << EOF\n${templ}\n${extempl}\nEOF" | sh > {{ $c.path }}/{{ $f.file }}
    {{- else }}
    ${cmd} "cat << EOF\n${templ}\nEOF" | sh > {{ $c.path }}/{{ $f.file }}
    {{- end }}
    {{- if $c.debug }}
    cat {{ $c.path }}/{{ $f.file }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- if eq $deploymentType "StatefulSet" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  {{- if .Values.canary }}
  name: {{ .Chart.Name }}-canary
  {{- else }}
  name: {{ .Chart.Name }}
  {{- end }}
  labels:
    {{- include "propeller.chartLabels" . | indent 4 }}
    {{- include "propeller.helmLabels" . | indent 4 }}
    {{- range $k, $v := .Values.labels }}
    {{ $k }}: "{{ $v }}"
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "propeller.chartLabels" . | indent 6 }}
  {{- if .Values.canary }}
  serviceName: {{ .Chart.Name }}-canary
  {{- else }}
  serviceName: {{ .Chart.Name }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "propeller.chartLabels" . | indent 8 }}
    spec:
      {{- if .Values.canary }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-canary
      {{- else }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      {{- if or (or .Values.dataPath (or .Values.appInitializement .Values.logPath) ) (or .Values.initContainers .Values.container.secrets ) }}
      initContainers:
      {{- if .Values.dataPath}}
      - name: {{ .Chart.Name }}-init-datapath
        securityContext:
          privileged: true
        image: {{ .Values.toolboxImage | default "busybox" }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        command:
          - sh
          - -c
          - {{ if .Values.uid }}chown {{ .Values.uid }}:{{ .Values.uid }} -R {{ .Values.dataPath }} && {{ end }}chmod 0766 -R {{ .Values.dataPath }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        volumeMounts:
        - name: {{ .Chart.Name }}-datapath
          mountPath: {{ .Values.dataPath }}
      {{- end }}
      {{- if .Values.logPath}}
      - name: {{ .Chart.Name }}-init-logpath
        securityContext:
          privileged: true
        image: {{ .Values.toolboxImage | default "busybox" }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        command:
          - sh
          - -c
          - {{ if .Values.uid }}chown {{ .Values.uid }}:{{ .Values.uid }} -R {{ .Values.logPath }} && {{ end }}chmod 0766 -R {{ .Values.logPath }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        volumeMounts:
        {{- include "propeller.logPathVolumeMount" . | indent 8 }}
      {{- end }}
      {{- if .Values.appInitializement }}
      {{- $init := .Values.appInitializement }}
      - name: {{ .Chart.Name }}-prepare
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        command:
        - sh
        - -c
        {{- range $i, $c := $init.configFiles }}
        - sh /etc/config/prepare-{{ $i }}.sh && cp -rf {{ $c.path }}/* /data/{{ $.Chart.Name }}-appconfig-{{ $i }}/
        {{- end }}
        volumeMounts:
        {{- range $i, $c := $init.configFiles }}
        - name: {{ $.Chart.Name }}-prepare-{{ $i }}
          mountPath: /etc/config/prepare-{{ $i }}.sh
          subPath: prepare-{{ $i }}.sh
        - name: {{ $.Chart.Name }}-appconfig-{{ $i }}
          mountPath: /data/{{ $.Chart.Name }}-appconfig-{{ $i }}
        {{- end }}
        {{- if .Values.configMaps }}
        {{- $cmParams := dict "configMaps" .Values.configMaps "container" .Chart.Name "chartName" .Chart.Name -}}
        {{- include "propeller.expandConfigMapByContainer" $cmParams | indent 8 }}
        {{- end }}
        {{- if or $init.env ( or $init.secrets $init.configMaps ) }}
        env:
        {{- if $init.env -}}
        {{- include "propeller.expandEnv" $init.env | indent 8 -}}
        {{- end -}}
        {{- $secrets := dict "secrets" $init.secrets "ref" .Values.propeller -}}
        {{- include "propeller.expandSecrets" $secrets | indent 8 -}}
        {{- end }}
      {{- if and $init.secrets $.Values.preCheckNetwork }}
      {{- $secrets := dict "secrets" $init.secrets "ref" $.Values.propeller "container" "init" "toolboxImage" $.Values.toolboxImage -}}
      {{- include "propeller.checkConnectionBySecrets" $secrets | indent 6 -}}
      {{- end }}
      {{- end }}
      {{- if and .Values.container.secrets .Values.preCheckNetwork }}
      {{- $secrets := dict "secrets" .Values.container.secrets "ref" .Values.propeller "container" .Chart.Name "toolboxImage" .Values.toolboxImage -}}
      {{- include "propeller.checkConnectionBySecrets" $secrets | indent 6 -}}
      {{- end }}
      {{- if .Values.initContainers }}
      {{- range $init := .Values.initContainers }}
      - name: {{ $init.name }}
        {{- if eq $init.image "SAME_AS_CONTAINER" }}
        image: "{{ $.Values.image.repository }}:{{ $.Chart.AppVersion }}"
        {{- else }}
        image: {{ $init.image }}
        {{- end }}
        imagePullPolicy: {{ $.Values.image.pullPolicy | default "IfNotPresent" }}
        command:
        {{- toYaml $init.command | nindent 10 }}
        {{- if or $init.volumeMounts (eq $init.image "SAME_AS_CONTAINER") }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        volumeMounts:
        {{- if $.Values.appInitializement }}
        {{- range $i, $c := $.Values.appInitializement.configFiles }}
        - name: {{ $.Chart.Name }}-appconfig-{{ $i }}
          mountPath: {{ $c.path }}
        {{- end }}
        {{- end }}
        {{- if $.Values.dataPath }}
        - name: {{ $.Chart.Name }}-datapath
          mountPath: {{ $.Values.dataPath }}
        {{- end }}
        {{- if $.Values.logPath }}
        {{- include "propeller.logPathVolumeMount" $ | indent 8 }}
        {{- end }}
        {{- if $init.volumeMounts }}
        {{- toYaml $init.volumeMounts | nindent 10 }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      containers:
      {{- if .Values.extraContainers }}
      {{- $prependContainerParams := dict "prependContainers" true "src" . }}
      {{- include "propeller.expandExtraContainers" $prependContainerParams | indent 6 }}
      {{- end }}
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        {{- if and .Values.container .Values.container.port }}
        ports:
        - containerPort: {{ .Values.container.port }}
          name: http
        {{- else }}
        {{- if and .Values.container .Values.container.ports }}
        ports:
        {{- range $p := .Values.container.ports }}
        - containerPort: {{ $p.port }}
          name: {{ $p.name | default ( printf "port-%s" ( toString $p.port ) ) }}
        {{- end }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        {{- if and .Values.lifecycle .Values.lifecycle.postStartCommand }}
        lifecycle:
          postStart:
            exec:
              command:
              {{- range $e := .Values.lifecycle.postStartCommand }}
              - {{ $e }}
              {{- end }}
        {{- end }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}
        {{- if or (and .Values.appInitializement .Values.appInitializement.configFiles ) (or .Values.configMaps .Values.logPath ) }}
        volumeMounts:
        {{- if .Values.appInitializement }}
        {{- range $i, $c := .Values.appInitializement.configFiles }}
        - name: {{ $.Chart.Name }}-appconfig-{{ $i }}
          mountPath: {{ $c.path }}
        {{- end }}
        {{- end }}
        {{- if .Values.configMaps }}
        {{- $cmParams := dict "configMaps" .Values.configMaps "container" .Chart.Name "chartName" .Chart.Name -}}
        {{- include "propeller.expandConfigMapByContainer" $cmParams | indent 8 }}
        {{- end }}
        {{- if .Values.dataPath }}
        - name: {{ .Chart.Name }}-datapath
          mountPath: {{ .Values.dataPath }}
        {{- end }}
        {{- if .Values.logPath }}
        {{- include "propeller.logPathVolumeMount" . | indent 8 }}
        {{- end }}
        {{- end }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        {{- if .Values.env -}}
        {{- include "propeller.expandEnv" .Values.env | indent 8 -}}
        {{- end -}}
        {{- if and .Values.container .Values.container.secrets -}}
        {{- $secrets := dict "secrets" .Values.container.secrets "ref" .Values.propeller -}}
        {{- include "propeller.expandSecrets" $secrets | indent 8 -}}
        {{- end }}
      {{- if .Values.extraContainers }}
      {{- $appendContainerParams := dict "prependContainers" false "src" . }}
      {{- include "propeller.expandExtraContainers" $appendContainerParams | indent 6 }}
      {{- end }}
      {{- if or (and .Values.appInitializement .Values.appInitializement.configFiles ) (or .Values.configMaps .Values.logPath ) }}
      volumes:
      {{- if .Values.appInitializement }}
      {{- range $i, $c := .Values.appInitializement.configFiles }}
      - name: {{ $.Chart.Name }}-appconfig-{{ $i }}
        emptyDir: {}
      - name: {{ $.Chart.Name }}-prepare-{{ $i }}
        configMap:
          name: {{ include "propeller.appName" $ }}-prepare-{{ $i }}
          items:
          - key: prepare-{{ $i }}.sh
            path: prepare-{{ $i }}.sh
      {{- end }}
      {{- end }}
      {{- if .Values.configMaps }}
      {{- range $c := .Values.configMaps }}
      - name: {{ $.Chart.Name }}-{{ $c.name }}
        configMap:
          name: {{ include "propeller.appName" $ -}}-{{ $c.name }}
          items:
          {{- range $ckey, $_ := $c.data }}
          - key: {{ $ckey }}
            path: {{ $ckey }}
          {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.logPath }}
      - name: {{ .Chart.Name }}-logpath
        hostPath:
          path: /var/log/k8sapps
          type: DirectoryOrCreate
      {{- end }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Chart.Name }}-datapath
      labels:
        {{- include "propeller.chartLabels" . | indent 8 }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.storage.requests }}
{{- end }}
{{- end }}