{{- define "propeller.virtualservice.tpl" -}}
{{- if and .Values.service (or .Values.service.gateway .Values.service.gateways) }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "propeller.appName" . }}
  labels:
    {{- include "propeller.chartLabels" . | indent 4 }}
    {{- include "propeller.helmLabels" . | indent 4 }}
spec:
  hosts:
  {{- if .Values.service.hosts }}
  {{- toYaml .Values.service.hosts | indent 4 }}
  {{- else }}
  - "*"
  {{- end }}
  gateways:
  {{- if .Values.service.gateways }}
  {{- range $_, $gateway := .Values.service.gateways }}
  - {{ $gateway }}
  {{- end }}
  {{- else }}
  - {{ .Values.service.gateway }}
  {{- end }}
  http:
  {{- if .Values.service.extraPorts }}
  {{- range $p := .Values.service.extraPorts }}
  {{- if and $p.path $p.port }}
  - match:
    - uri:
        prefix: /{{ $.Release.Namespace }}/{{- include "propeller.appName" $ -}}/{{ trimAll "/" $p.path }}/
    rewrite:
      {{- if $p.rewriteroot }}
      uri: /
      {{- else }}
      uri: /{{ trimAll "/" $p.path }}/
      {{- end }}
    route:
    - destination:
        host: {{ include "propeller.appName" $ }}
        port:
          number: {{ $p.port }}
    {{- if $.Values.service.mirror }}
    mirror:
      {{ toYaml $.Values.service.mirror | nindent 6 }}
    {{- end }}
    {{- if $.Values.service.mirrorPercent }}
    mirrorPercent: {{ $.Values.service.mirrorPercent }}
    {{- end }}
    {{- if $p.timeout }}
    timeout: {{ $p.timeout }}
    {{- else }}
    timeout: 30s
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  - match:
    - uri:
        prefix: /{{ .Release.Namespace }}/{{- include "propeller.appName" . -}}/
    {{- if not ( or ( hasPrefix "webapp" .Values.labels.type ) ( hasPrefix "webhtml" .Values.labels.type ) ) }}
    - uri:
        exact: /{{ .Release.Namespace }}/{{- include "propeller.appName" . }}
    {{- end }}
    {{- if eq .Values.labels.type "webapp0" }}
    rewrite:
      uri: /{{ .Chart.Name }}/
    {{- else }}
    rewrite:
      uri: /
    {{- end }}
    route:
    - destination:
        host: {{ include "propeller.appName" . }}
        port:
          number: {{ .Values.service.port }}
    {{- if .Values.service.mirror }}
    mirror:
      {{ toYaml .Values.service.mirror | nindent 6 }}
    {{- end }}
    {{- if .Values.service.mirrorPercent }}
    mirrorPercent: {{ .Values.service.mirrorPercent }}
    {{- end }}
    {{- if .Values.service.timeout }}
    timeout: {{ .Values.service.timeout }}
    {{- else }}
    timeout: 30s
    {{- end }}
  {{- if or ( hasPrefix "webapp" .Values.labels.type ) ( hasPrefix "webhtml" .Values.labels.type ) }}
  - match:
    - uri:
        exact: /{{ .Release.Namespace }}/{{- include "propeller.appName" . }}
    redirect:
      uri: /{{ .Release.Namespace }}/{{- include "propeller.appName" . -}}/
    {{- if .Values.service.timeout }}
    timeout: {{ .Values.service.timeout }}
    {{- else }}
    timeout: 30s
    {{- end }}
  {{- end }}
  {{- if .Values.service.prefixUris }}
  {{- range $uri := .Values.service.prefixUris }}
  - match:
    - uri:
        {{- if $.Values.canary }}
        prefix: /canary/{{ trimPrefix "/" $uri }}
        {{- else }}
        prefix: {{ $uri }}
        {{- end }}
    {{- if $.Values.canary }}
    rewrite:
      uri: /{{ trimPrefix "/" $uri }}
    {{- end }}
    route:
    - destination:
        host: {{ include "propeller.appName" $ }}
        port:
          number: {{ $.Values.service.port }}
    {{- if $.Values.service.mirror }}
    mirror:
      {{ toYaml $.Values.service.mirror | nindent 6 }}
    {{- end }}
    {{- if $.Values.service.mirrorPercent }}
    mirrorPercent: {{ $.Values.service.mirrorPercent }}
    {{- end }}
    {{- if $.Values.service.timeout }}
    timeout: {{ $.Values.service.timeout }}
    {{- else }}
    timeout: 30s
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
